build: fix errors in the build process
throw Error('Dynamic require of "' + x + '" is not supported');
          ^

  Error: Dynamic require of "net" is not supported
      at file:///home/runner/work/_actions/redhat-plumbers-in-action/auto-merge/v3/dist/main.js:11:9
      at node_modules/tunnel/lib/tunnel.js (file:///home/runner/work/_actions/redhat-plumbers-in-action/auto-merge/v3/dist/main.js:41:15)
      at __require2 (file:///home/runner/work/_actions/redhat-plumbers-in-action/auto-merge/v3/dist/main.js:14:50)
      at node_modules/tunnel/index.js (file:///home/runner/work/_actions/redhat-plumbers-in-action/auto-merge/v3/dist/main.js:270:22)
      at __require2 (file:///home/runner/work/_actions/redhat-plumbers-in-action/auto-merge/v3/dist/main.js:14:50)
      at file:///home/runner/work/_actions/redhat-plumbers-in-action/auto-merge/v3/dist/main.js:39167:22
      at ModuleJob.run (node:internal/modules/esm/module_job:430:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:661:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)